### ISSUE TITLE
Question: We are not really 'talking' to endpoints provided by Spring-Boot?

### ISSUE THREAD

**Issue by jbellmann** [lavcraft/grpc-spring-boot-starter#2]
Hi,
I'm new to gRPC and found this project via searching.
My first question would be:
We are not 'talking' to endpoints provided by the Spring-Boot app. Instead we are connecting to the 'embedded gRPC-Server' which is provided by Netty, right? Why do we need that wrapper when the communication is via Http. Does Spring-Boot or Tomcat not provide 'connectors' for that yet? What's with Jetty or Undertow, do they?

My second question:
Why would it be good thing to have multiple embedded servers running? At least I understand your starter in that way that it will spawn as many embedded servers as I configure. What do you had in mind when designing it that way. I found another 'grpc-spring-boot-starter' that does not go with multiple server-instances. Why did you so?

Regards
Jörg

**Comment by lavcraft** [comment]
Hello, thanks for asking.
1. gRPC depends on Netty. Jetty and Undertown don't provide required functions. And grpc developing for netty and use only with it. gRPC require HTTP2, not HTTP. Now, classic spring-boot app does't support http2 as main protocol. I try to create lightweight starter, which don't need spring "web" and start extremely fast - this is a main cause for exclude spring "web" and use only spring-boot skeleton for running and configuring app
2. It is advanced functionality. Only for my test and it does not matter. I needed to bind some server to public/private IP address, but now it don't needed.

Regards
Kirill

**Comment by jbellmann** [comment]
Thank you for answering.
